---
- name: execute script and get result back.
  hosts: 169.57.13.100

  tasks:
    - name: Execute the script
      shell: sh /root/eca/slack.sh
      failed_when: false
      register: mypass
    - name: Print the script result
      debug:
        msg: "{{ mypass }}"
        
    - name: To ping to Slack to send message
      slack:
         token: T4W1S5P34/B02MEUC40E9/iBeMJQKNdwG67tu90pxlPXGZ
         domain: hooks.slack.com
         channel: '#ansible_eca_test'
         msg: "{{mypass}}"    
      when: mypass | regex_search('breached')
      
    - name: fail the play if file system is within threshold
      fail:
        msg: "the command failed"
      when: mypass | regex_search('threshold')
